# Generated by Django 3.0.6 on 2020-06-24 22:24

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('min_room_temp', models.FloatField(blank=True, null=True)),
                ('max_room_temp', models.FloatField(blank=True, null=True)),
                ('current_temp', models.FloatField(blank=True, null=True)),
                ('current_temp_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('temp', 'Temperature'), ('hum', 'Humidity')], default='temp', max_length=20)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('current_state', models.CharField(blank=True, max_length=10, null=True)),
                ('states', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=55, null=True, size=5)),
                ('state_values', django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=30, null=True, size=5)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Room')),
            ],
        ),
    ]
