# Generated by Django 3.0.7 on 2020-07-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
